_wandb:
    value:
        cli_version: 0.26.1
        e:
            vtylfd4lpqmbv8mpdxbndvqm1o4qaicm:
                args:
                    - --wandb
                codePath: scripts/single_hour_inference.py
                codePathLocal: scripts/single_hour_inference.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "2163217457152"
                        used: "421399506944"
                email: albertopedalino98@gmail.com
                executable: /home/apedalino/physiq_pv/.venv/bin/python
                git:
                    commit: a2a6461884dd79845f0b22ca1f4e0e4abfe34593
                    remote: https://github.com/AlbertoPedalino/physiq-pv.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                      uuid: GPU-43f85ccf-9817-c729-ceca-2dbf6345a835
                host: newzealand
                memory:
                    total: "134391025664"
                os: Linux-6.8.0-110-generic-x86_64-with-glibc2.39
                program: /home/apedalino/physiq_pv/scripts/single_hour_inference.py
                python: CPython 3.12.3
                root: /home/apedalino/physiq_pv
                startedAt: "2026-05-11T12:26:28.783273Z"
                writerId: vtylfd4lpqmbv8mpdxbndvqm1o4qaicm
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.12.3
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
checkpoint_dir:
    value: checkpoints
hour_index:
    value: null
n_features:
    value: 14
n_plants:
    value: 1116
plant_index:
    value: null
seq_len:
    value: 24
target_time:
    value: "2019-09-25 13:00:00"
