_wandb:
    value:
        cli_version: 0.26.1
        e:
            vtyk6t7xn1w9e4wm4m3yzmd5c26k678e:
                args:
                    - --mode
                    - pvgis_stgnn
                    - --pvgis-dir
                    - /data/SentinelPV/pvgis_data/data/pvgis_summed_irradiance
                    - --train-years
                    - 2016,2017,2018
                    - --test-year
                    - "2019"
                    - --anomaly-scores
                    - outputs/pvgis_anomaly_2019_2005_2023_w15_q0975/pvgis_climatology_scores.csv
                    - --device
                    - cuda
                    - --out-dir
                    - outputs/wandb_pvgis_stgnn/{wandb_run_id}
                    - --wandb
                    - --wandb-entity
                    - albertopedalino-politecnico-di-torino
                    - --wandb-project
                    - PhysiQ-PV
                    - --batch_size=16
                    - --clc_eta=10
                    - --coverage_target=0.95
                    - --dropout=0.3
                    - --ensemble_predictions_dir=auto
                    - --epochs=5
                    - --feature_set=full
                    - --horizon=1
                    - --lr=0.001
                    - --mc_dropout
                    - --mc_samples=20
                    - --model_type=stgnn_enhanced_dropout
                    - --pv_target_clip_max=none
                    - --save_ensemble_predictions
                    - --seed=1
                    - --seq_len=24
                    - --target_variable=pv_power_output
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "2163217457152"
                        used: "1171686744064"
                email: albertopedalino98@gmail.com
                executable: /home/apedalino/physiq_pv/.venv/bin/python
                git:
                    commit: 7d02588268b0068260b59ac93f92173259d653a2
                    remote: https://github.com/AlbertoPedalino/physiq-pv.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                      uuid: GPU-43f85ccf-9817-c729-ceca-2dbf6345a835
                host: newzealand
                memory:
                    total: "134391025664"
                os: Linux-6.8.0-110-generic-x86_64-with-glibc2.39
                program: /home/apedalino/physiq_pv/main.py
                python: CPython 3.12.3
                root: /home/apedalino/physiq_pv
                startedAt: "2026-06-11T10:49:20.053033Z"
                writerId: vtyk6t7xn1w9e4wm4m3yzmd5c26k678e
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
                - 16
                - 41
                - 62
            "4": 3.12.3
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
anomaly_scores:
    value: outputs/pvgis_anomaly_2019_2005_2023_w15_q0975/pvgis_climatology_scores.csv
batch_size:
    value: 16
calibration_anomaly_scores:
    value: null
calibration_eps:
    value: 1e-06
calibration_strategy:
    value: global
calibration_years:
    value: null
clc_eta:
    value: 10
coverage_target:
    value: 0.95
device:
    value: cuda
dropout:
    value: 0.3
enable_posthoc_calibration:
    value: false
ensemble_predictions_dir:
    value: auto
epochs:
    value: 5
feature_set:
    value: full
hidden_size:
    value: 64
horizon:
    value: 1
lr:
    value: 0.001
lstm_layers:
    value: 2
max_calibration_samples:
    value: null
max_test_samples:
    value: null
max_train_samples:
    value: null
mc_dropout:
    value: true
mc_samples:
    value: 20
min_calibration_samples_per_stratum:
    value: 1000
mode:
    value: pvgis_stgnn
model_type:
    value: stgnn_enhanced_dropout
n_features:
    value: 11
pv_target_clip_max:
    value: none
save_ensemble_predictions:
    value: true
seed:
    value: 1
selected_features:
    value:
        - temperature_2m
        - solar_irradiance_poa
        - wind_speed_10m
        - sin_elev
        - cos_elev
        - kt
        - kt_std_3h
        - dghi_dt
        - dni_norm
        - dhi_norm
        - pv_lag_pvgis
seq_len:
    value: 24
skip_predictions_csv:
    value: false
target_variable:
    value: pv_power_output
test_year:
    value: 2019
train_years:
    value: 2016,2017,2018
wandb_log_predictions:
    value: false
